apktool = '''java -jar C:\\utill\\apktool.jar'''
signer = '''jarsigner -verbose -sigalg MD5withRSA -digestalg SHA1 -keystore'''
key = '''C:\\utill\\keystore\\testsig.jks'''
keyPass = '''-storepass 123456'''
alias = '''testsig'''
screencapPath = '''D:\\ScreenCap'''
aapt = '''C:\\Android\\sdk\\build-tools\\25.0.0\\aapt.exe dump badging'''